# @file
# .travis.yml - PKP Plugins Integration

dist: bionic
os: linux
language: php

addons:
  postgresql: "9.5"
  apt:
    update: true

sudo: required

php:
  - 7.3
  - 7.4
  - 8.0
env:
  - APPLICATION=ojs BRANCH=stable-3_3_0 TEST=mysql
  - APPLICATION=ojs BRANCH=stable-3_3_0 TEST=pgsql

install:
  # Prepare OJS/OMP environment
  - git clone -b ${BRANCH} https://github.com/pkp/${APPLICATION} ~/${APPLICATION}
  - cd ~/${APPLICATION}
  - git submodule update --init --recursive
  - source lib/pkp/tools/travis/prepare-tests.sh
  - lib/pkp/tools/travis/prepare-webserver.sh
  # Install Schematron validation and XML munging toolset
  - sudo apt-get install python3-lxml xmlstarlet
  - wget -q "https://eruditps.docs.erudit.org/_downloads/f0f9fb861e01a47df2ce48f588524d29/erudit-style-0.3.sch"
  # Build/install dependencies
  - lib/pkp/tools/travis/install-composer-dependencies.sh
  - npm i g -npm && npm install && npm run build
  - cp -r ${TRAVIS_BUILD_DIR} ~/${APPLICATION}/plugins/oaiMetadataFormats/oaiJats
  # This plugin also requires the OAI JATS plugin (they are tested together via this script)
  - git clone -b ${BRANCH} https://github.com/pkp/jatsTemplate plugins/generic/jatsTemplate
  # Install OJS/OMP & prep data environment
  - $(npm bin)/cypress run --spec "cypress/tests/data/10-Installation.spec.js,cypress/tests/data/20-CreateContext.spec.js,cypress/tests/data/40-CreateUsers.spec.js,cypress/tests/data/50-CreateIssues.spec.js,cypress/tests/data/50-CreateSections.spec.js,cypress/tests/data/60-content/AmwandengaSubmission.spec.js"

script:
  - $(npm bin)/cypress run --config integrationFolder=plugins/oaiMetadataFormats/oaiJats/cypress/tests
  # Fetch a JATS document through oaiJats, removing the OAI-PMH wrapper using xmlstarlet
  - wget -q -O - "http://localhost/index.php/publicknowledge/oai?verb=ListRecords&metadataPrefix=jats" | xmlstarlet sel -N x="https://jats.nlm.nih.gov/publishing/1.1/" -t -c "(//x:article)[1]" > jats.xml
  - python3 plugins/oaiMetadataFormats/oaiJats/validate.py jats.xml erudit-style-0.3.sch

after_failure:
  - cat error.log
  - sudo apt-get install sharutils
  - tar cz cypress/screenshots | uuencode /dev/stdout
